server.port=8080
spring.application.name=heatgrid-java-backend

# database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/HeatGrid_DB 
spring.datasource.username=root
spring.datasource.password=root

# JPA configuartion --- JPA (Java Persistence API) is a specification for managing relational data in Java applications.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

